---
title: "OpenHDF5"
author: "Holly Andrews"
date: "June 20, 2016"
output: html_document
---
New sentence.
## About this code

```{r load-libraries}
#load libraries
library(raster)
library(rhdf5)
library(rgdal)
```


## Let's open a file

```{r select-file}
f <- "../NEONdata/D17-California/TEAK/2013/spectrometer/reflectance/Subset3NIS1_20130614_100459_atmcor.h5"

#view h5 structure
h5ls(f)
```

## Import Spatial Information

```{r import-spatial-info}
#import spatial info
mapInfo <- h5read(f, 
                  "map info",
                  read.attributes=TRUE)
```

## Get reflectance metadata

```{r get-refl-metadata}
#read in reflectance data attributes
reflInfo <- h5readAttributes(f, "Reflectance")
#define scale factor
scaleFactor <- reflInfo$`Scale Factor`
#define no data value
noDataValue <- as.numeric(reflInfo$`data ignore value`)

```

## Import Data Dims

```{r import-dims}
# open file for viewing
fid <- H5Fopen(f)
#open reflectance data
did <- H5Dopen(fid, "Reflectance")
#grab data dimensions
sid <- H5Dget_space(did)
dims <- H5Sget_simple_extent_dims(sid)$size

#close all open connections
H5Sclose(sid)
H5Dclose(did)
H5Fclose(fid)
```

## Read in reflectance data

```{r read-data}
#extract slice of H5 file
b56 <- h5read(f, "Reflectance", index=list(1:dims[1], 1:dims[2], 56))
```

## Convert data to matrix

```{r convert-matrix}
#reassign b56 to matrix
b56 <- b56[,,1]
#let's plot data!
image(b56)
image(log(b56),main="log transformed data")
hist(b56)
```

## Time to clean our data

```{r data-clean-up}
# assign no data values to object
b56[b56=noDataValue] <- NA
#apply scale factor
b56 <- b56 / scaleFactor
hist(b56)
```

## Transpose Data

```{r transpose-data}
b56 <- t(b56)
image(log(b56))
```

## Create spatial extent

```{r create-spatial-extent}
#split out mapInfo object
mapInfo <- strsplit(mapInfo,",")
mapInfo <- unlist(mapInfo)

#defining upper left hand corner coordinate 
xMin <- as.numeric(mapInfo[4])
yMax <- as.numeric(mapInfo[5])

#get spatial resolution
xRes <- as.numeric(mapInfo[6])
yRes <- as.numeric(mapInfo[7])

#calculate xMax and yMin
xMax <- xMin + (dims[1]*xRes)
yMin <- yMax - (dims[2]*yRes)

```

## Create spatial extent

```{r create-extent}
#create extent object
rasExt <- extent(xMin,xMax,yMin,yMax)

#create raster object
b56r <- raster(b56, crs=CRS("+init=epsg:32611"))
extent(b56r) <- rasExt
plot(b56r,main="Spatially referenced data")
```

## Import NEON functions

```{r import-using-functions}
library(devtools)
install_github("lwasser/neon-aop-package/neonAOP")
library(neonAOP)

b55 <- open_band(f,55,32611)
plot(b55)

#import several bands 
bands <- c(58,34,19) #must be decreasing to get RGB image

#create raster stack
RGBStack <- create_stack(f,bands,32611)

#plot RGB image
plotRGB(RGBStack,stretch='lin')
```

